[workspace]
members = [
  "tauri",
  "lib",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["you"]
license = ""
repository = ""
# this was set by tauri
rust-version = "1.60"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
