/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function start(minutes: number, seconds: number, timerid: string) {
    return invoke()<null>("start", { minutes,seconds,timerid })
}

export function stop(id: string) {
    return invoke()<null>("stop", { id })
}

export function pause(id: string) {
    return invoke()<null>("pause", { id })
}

export function play(id: string) {
    return invoke()<null>("play", { id })
}

export function update(id: string, duration: number) {
    return invoke()<null>("update", { id,duration })
}


