export const colors = [
  '--col-bg',
  '--col-bg-alt',
  '--col-base0',
  '--col-base1',
  '--col-base2',
  '--col-base3',
  '--col-base4',
  '--col-base5',
  '--col-base6',
  '--col-base7',
  '--col-base8',
  '--col-fg-alt',
  '--col-fg',
  '--col-grey',
  '--col-red',
  '--col-orange',
  '--col-green',
  '--col-teal',
  '--col-yellow',
  '--col-blue',
  '--col-dark-blue',
  '--col-magenta',
  '--col-violet',
  '--col-cyan',
  '--col-dark-cyan',
] as const;

export const palette = [
  '--color-backgroundSubtle',
  '--color-background',
  '--color-backgroundBright',
  '--color-backgroundBrightest',
  '--color-fgDim',
  '--color-fg',
  '--color-fgBrightest',
  '--color-primary',
  '--color-bright',
  '--color-secondary',
  '--color-tertiary',
  '--color-error',
  '--color-warning',
  '--color-good',
] as const;
